config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get("/", to: "homepage#index", as: :root)

  get("/contact_us", to: "homepage#contact")

  post("/contact_us/process", to: "homepage#process_contact", as: :process_contact)

  resource :session, only: [:new, :create, :destroy]
  resources :users

  resources :bookings, only: [:index] do
    resources :booking_archivings, only: [:create]
    
    get :archived_bookings, on: :collection
  end
  
  resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
    resources :occurence_archivings, shallow: true, only: [:create]
    
    resources :bookings, shallow: true, only: [:create, :destroy] do
      resources :payments, shallow: true, only: [:new, :create]
    end

    get :booked, on: :collection
    get :archived_occurences, on: :collection
  end

  resources :gym_classes do
    resources :occurences, only: [:new, :create, :index, :destroy]
  end


  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create, :show, :index, :update, :destroy] do
        get :current, on: :collection
      end
      
      resources :bookings, only: [:index, :show]  

      resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
        
        resources :bookings, shallow: true, only: [:create, :destroy]

        get :booked, on: :collection
      end

      resources :gym_classes do
        resources :occurences, only: [:new, :create, :index, :destroy]
      end
    
    end
    match "*unmatched", via: :all, to: "application#not_found"
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index
        render :index
    end

    def contact
    end

    def process_contact
        @full_name = params[:full_name]
        @message = params[:message]
        @email = params[:email]

        render :thank_you
    end
end

app/views/homepage/contact.html.erb
<div class="hero">
    <%= image_tag "athletes-endurance-energy-685534.jpg", style: "width: 100%;" %>
    <h3 class="hero-text" >Contact Us</h3>

    <div class="form-group hero-text" >
        <%= form_tag(process_contact_path) do %>
            <div>
                <%= label_tag :full_name, nil, class: "control-label" %>  
                <%= text_field_tag :full_name, nil, class: "form-control" %>
            </div>
            <div>
                <%= label_tag :email, nil, class: "control-label"  %>
                <%= email_field_tag :email, nil, class: "form-control" %>
            </div>
            <div>
                <%= label_tag :message, nil, class: "control-label"  %>
                <%= text_area_tag :message, nil, cols:50, rows: 10, class: "form-control"  %>
            </div>
            <%= submit_tag("Contact Us", class: "btn btn-secondary bg-light text-secondary m-5") %>
        <% end %>
    </div>

</div>

app/views/homepage/index.html.erb
<div class="hero" >
    <%= image_tag "athletes-endurance-energy-685534.jpg", style: "width: 100%;" %>
    <div class="hero-text" >
        <h1> Welcome to the Home Page of Gymook</h1>
        <button class="btn bg-light" >
            <%= link_to("Contact Us", contact_us_path, class: "text-secondary") %>
        </button>
    </div>
</div>

app/views/homepage/thank_you.html.erb
<h1>Thank you!</h1>
<p>
    Thank you <strong><%= @full_name %></strong>, on of our coaches will contact you
    shortly. Please be patient with us. Thanks for getting in touch.
</p>

<p>
    <strong>Your message was:</strong>
    <%= @message %>
</p>