config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get("/", to: "homepage#index", as: :root)

  get("/contact_us", to: "homepage#contact")

  post("/contact_us/process", to: "homepage#process_contact", as: :process_contact)

  resource :session, only: [:new, :create, :destroy]
  resources :users

  resources :bookings, only: [:index] do
    resources :booking_archivings, only: [:create]
    
    get :archived_bookings, on: :collection
  end
  
  resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
    resources :occurence_archivings, shallow: true, only: [:create]
    
    resources :bookings, shallow: true, only: [:create, :destroy] do
      resources :payments, shallow: true, only: [:new, :create]
    end

    get :booked, on: :collection
    get :archived_occurences, on: :collection
  end

  resources :gym_classes do
    resources :occurences, only: [:new, :create, :index, :destroy]
  end


  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create, :show, :index, :update, :destroy] do
        get :current, on: :collection
      end
      
      resources :bookings, only: [:index, :show]  

      resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
        
        resources :bookings, shallow: true, only: [:create, :destroy]

        get :booked, on: :collection
      end

      resources :gym_classes do
        resources :occurences, only: [:new, :create, :index, :destroy]
      end
    
    end
    match "*unmatched", via: :all, to: "application#not_found"
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :occurence


  validates(
    :user_id,
    presence: true
  )
  validates(
    :occurence_id,
    uniqueness: {
      scope: :user_id,
      message: "You have already made a booking for this occurence!"
    }
  )

  include AASM

  aasm whiny_transitions: false do
    state :active, initial: true
    state :archived
    
    event :archive do
      transitions from: :active, to: :archived
    end

    event :activate do
      transitions from: :archived, to: :active
    end
  end

  def self.viewable
    where(aasm_state: [:active])
  end

  def self.archived
    where(aasm_state: [:archived])
  end

  scope(:recent, -> { order(created_at: :desc).limit(1000) })
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::ApplicationController
    before_action :authenticate_user!

    def create
        occurence = Occurence.find(params[:occurence_id])
        gym_class = occurence.gym_class
        booking = Booking.new(occurence: occurence, user: current_user)

        if !can?(:book, occurence)
            render json: { status: 401 }, status: 401
        elsif booking.save!
            render json: {id: booking.id}
        else
            render json: { status: 500 }, status: 500 
        end
    end

    def index
        bookings = Booking.all.viewable.order(created_at: :desc)
        render json: bookings
    end

    def show
        booking = Booking.find(params[:id])
        render json: booking
    end

    def destroy
        booking = current_user.bookings.find(params[:id])
        occurence = booking.occurence
        gym_class = occurence.gym_class

        if can?(:delete, booking)
            booking.destroy!
            render json: { status: 200 }, status: 200
        else
            render json: { status: 403 }, status: 403
        end
    end

    private
    def booking
        @booking ||= Booking.find(params[:id])
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :authenticate_user!

    def create
        occurence = Occurence.find(params[:occurence_id])
        gym_class = occurence.gym_class
        booking = Booking.new(occurence: occurence, user: current_user)

        if !can?(:book, occurence)
            flash[:warning] = "You can not book your own occurence."
            redirect_to booked_occurences_path
        elsif booking.save
            # flash[:success] = "Your class was successfully booked."
            redirect_to new_booking_payment_path(booking.id)
        else
            flash[:danger] = booking.errors.full_messages.join(", ")
            redirect_to booked_occurences_path
        end

    end

    def index
        @bookings = Booking.all.viewable.order(created_at: :desc)
    end

    def show
        @booking = Booking.find(params[:id])
    end

    def destroy
        booking = current_user.bookings.find(params[:id])
        ocuurence = booking.occurence
        gym_class = ocuurence.gym_class

        if can?(:delete, booking)
            booking.destroy
            flash[:success] = "The booking was successfully cancelled"
        else
            flash[:warning] = "Can not cancel this booking, something went wrong..."
        end
        redirect_to booked_occurences_path
    end

    def archived_bookings
        @bookings = Booking.all.archived.order(created_at: :desc)
    end
end

app/helpers/api/v1/bookings_helper.rb
module Api::V1::BookingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_list.html.erb
<ul class="mt-2 bookings-list">
    <% @bookings.each do |booking| %>
        <li>
            <%= link_to("A #{booking.occurence.gym_class.class_type} booking", occurence_path(booking.occurence.id), class: "text-secondary" ) %>
            <%= link_to("by #{booking.user.full_name}", user_path(booking.user.id), class: "text-secondary") %>
            was done <%= time_ago_in_words(booking.created_at) %> ago. <br>
            <% if user_is_coach? %>
                <small>
                    <% if booking.active? && can?(:archive, booking) %>
                        <%= link_to(
                            "Archive Booking", 
                            booking_booking_archivings_path(booking), 
                            method: :post, 
                            data: {
                                message: "Are you sure you want to archive this booking?"
                            },
                            class: "text-secondary"
                            ) 
                        %>
                    <% elsif booking.archived? && can?(:activate, booking) %>
                        <%= link_to(
                            "Activate Booking",
                            booking_booking_archivings_path(booking),
                            method: :post,
                            data: {
                                message: "Are you sure you want to activate this booking?"
                            },
                            class: "text-secondary"
                            ) 
                        %>
                    <% end %>
                </small>
            <% end %>
        </li> <br>
    <% end %>
</ul>

app/views/bookings/archived_bookings.html.erb
<h3 class="m-2">List of all archived bookings</h3>

<%= render "list" %>

app/views/bookings/index.html.erb
<h3 class="m-2" >List of bookings ordered by the most recently booking made:</h3>

<%= render "list" %>