config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get("/", to: "homepage#index", as: :root)

  get("/contact_us", to: "homepage#contact")

  post("/contact_us/process", to: "homepage#process_contact", as: :process_contact)

  resource :session, only: [:new, :create, :destroy]
  resources :users

  resources :bookings, only: [:index] do
    resources :booking_archivings, only: [:create]
    
    get :archived_bookings, on: :collection
  end
  
  resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
    resources :occurence_archivings, shallow: true, only: [:create]
    
    resources :bookings, shallow: true, only: [:create, :destroy] do
      resources :payments, shallow: true, only: [:new, :create]
    end

    get :booked, on: :collection
    get :archived_occurences, on: :collection
  end

  resources :gym_classes do
    resources :occurences, only: [:new, :create, :index, :destroy]
  end


  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create, :show, :index, :update, :destroy] do
        get :current, on: :collection
      end
      
      resources :bookings, only: [:index, :show]  

      resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
        
        resources :bookings, shallow: true, only: [:create, :destroy]

        get :booked, on: :collection
      end

      resources :gym_classes do
        resources :occurences, only: [:new, :create, :index, :destroy]
      end
    
    end
    match "*unmatched", via: :all, to: "application#not_found"
  end

end

app/controllers/api/v1/gym_classes_controller.rb
class Api::V1::GymClassesController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def create
        gym_class = GymClass.new gym_class_params
        gym_class.user = current_user

        gym_class.save!
        render json: {id: gym_class.id}
    end

    def index
        gym_classes = GymClass.order(created_at: :desc)
        render json: gym_classes
    end

    def show
        render json: gym_class
    end

    def update
        gym_class.update! gym_class_params
        render json: {id: gym_class.id}
    end

    def destroy
        if can?(:delete, gym_class)
            gym_class.destroy
            render(json: {status: 200}, status: 200)
        else
            render(json: {status: 403}, status: 403)
        end
    end

    private
    def gym_class
        @gym_class ||= GymClass.find params[:id]
    end

    def gym_class_params
        params.require(:gym_class).permit(:class_type, :description, :cost, :maximum_clients)
    end
end

app/controllers/gym_classes_controller.rb
class GymClassesController < ApplicationController
    before_action :find_gym_class, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:show, :edit, :destroy]

    def new
        @gym_class = GymClass.new
        user = current_user
        if can?(:create, @gym_class)
            render :new
        else
            flash[:danger] = "Access Denied!"
            redirect_to root_path
        end
    end

    def create
        @gym_class = GymClass.new gym_class_params
        @gym_class.user = current_user
        if @gym_class.save
            flash[:primary] = "The Gym Class was successfully created!"
            redirect_to gym_class_path(@gym_class.id)
        else
            render :new
            flash[:alert] = "Oops, something went wrong... we couldn't create the Gym Class for you..."
        end
    end

    def index
        @gym_classes = GymClass.all.order(created_at: :desc)
    end

    def show
        @occurences = @gym_class.occurences.order(created_at: :desc)
    end

    def edit
    end

    def update
        if @gym_class.update gym_class_params
            redirect_to gym_class_path(@gym_class)
        else
            render :edit
        end
    end

    def destroy
        @gym_class.destroy
        redirect_to gym_classes_path
    end

    private
    def gym_class_params
        params.require(:gym_class).permit(:class_type, :description, :cost, :maximum_clients)
    end

    def find_gym_class
        @gym_class = GymClass.find params[:id]
    end

    def authorize_user!
        unless can?(:crud, @gym_class)
            flash[:danger] = "Access Denied!"
            redirect_to root_path
        end
    end
end

app/helpers/api/v1/gym_classes_helper.rb
module Api::V1::GymClassesHelper
end

app/helpers/gym_classes_helper.rb
module GymClassesHelper
end

app/views/gym_classes/_form.html.erb
<%#= form_with(model: @gym_class, local: true) do |f| %>
<%= simple_form_for @gym_class do |f| %>
    <%# if @gym_class.errors.present? %>
        <%#p class="form-errors" %>
            <%#= @gym_class.errors.full_messages.join(", ") %>
        <%#/p%>
    <%# end %>
    <%= f.input :class_type %>
    <%#div%>
        <%#= f.label :class_type, class: "control-label" %> <br>
        <%#= f.text_field :class_type, class: "form-control", placeholder: "Name the class you want to create" %>
    <%#/div%>
    <%= f.input :description %>
    <%#div%>
        <%#= f.label :description, class: "control-label" %> <br>
        <%#= f.text_area :description, cols: 50, rows: 10, class: "form-control" %>
    <%#/div%>
    <%= f.input :maximum_clients %>
    <%#div%>
        <%#= f.label :maximum_clients, class: "control-label" %> <br>
        <%#= f.text_field :maximum_clients, class: "form-control" %>
    <%#/div%>
    <%= f.input :cost  %>
    <%#div%>
        <%#= f.label :cost, class: "control-label" %> <br>
        <%#= f.text_field :cost, class: "form-control" %>
    <%#/div%>

    <%= f.submit "Create Gym Class", class: "m-2 btn btn-secondary bg-light text-secondary" %>
<% end %>

app/views/gym_classes/edit.html.erb
<h1>Edit Gym Class Template</h1>

<%= render "form" %>

app/views/gym_classes/index.html.erb
<ul class="gym_class-list card-group m-5 justify-content-center">
    <% @gym_classes.each do |gym_class| %>
        <div class="d-flex justify-content-start">
            <div class="card p-1 m-1 text-center" style="border-radius: 10px; max-width: 20rem;" >
                <div class="card-body">
                    <div class="card-title" >
                        <%= link_to(gym_class.class_type, gym_class_path(gym_class.id), class: "text-info") %>
                    </div>
                    <div class="card-text text-danger" >
                        Cost: $<%= gym_class.cost %>
                    </div> <br><br>
                    <div class="card-text" >
                        Maximum Clients per class: <%= gym_class.maximum_clients %>
                    </div> <br>
                    <div class="card-text" >
                        Created: <%= gym_class.created_at.strftime("%Y-%m-%d") %>
                    </div> <br>
                    <div class="card-text"  class="card-link" >
                        <%= link_to("New Class from this template", new_gym_class_occurence_path(gym_class.id), class: "text-success" ) %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</ul>

app/views/gym_classes/new.html.erb
<h1>Add a new Gym Class Template</h1>

<%= render "form" %>

app/views/gym_classes/show.html.erb
<h1><%= @gym_class.class_type %></h1>

<p> <%= @gym_class.description %> </p>

<div>
    <small>
        • Priced at: $<%= @gym_class.cost %> •
    </small>
    <small>
        Created by Coach <%= @gym_class.user&.full_name || "Delete" %> •
    </small>
    <small>
        <% if can?(:edit, @gym_class) %>
            <%= link_to("Edit", edit_gym_class_path(@gym_class.id), class: "text-secondary") %>
        <% end %>
    </small>
    <small>
        <% if user_is_admin? %>
            <% if can?(:delete, @gym_class) %>
                •
                <%= link_to(
                    "Delete", 
                    gym_class_path, 
                    method: :delete, 
                    class: "text-secondary", 
                    data: {
                        confirm: "Are you sure you want to delete this Gym Class?"
                }) %>
            <% end %>
        <% end %>
    </small> <br>
    <small>
        Created at: <%= @gym_class.created_at %>
    </small> <br>
    <small>
        Updated: <%= @gym_class.updated_at %>
    </small>
</div>

<h4> All <%= @gym_class.class_type %> Classes</h4>
<ul>
    <% @occurences.each do |occurence| %>
        <li id="<%= dom_id(occurence) %>" >
            <h6>
                The <%= occurence.gym_class.class_type %> on 
                <%= occurence.start_time.strftime("%A") %> 
                <%= occurence.start_time.strftime("%b") %>.
                <%= occurence.start_time.strftime("%-d") %>: 

            </h6>

            <p>
                <% if user_is_coach? %>
                    <%= link_to(
                        "This #{occurence.gym_class.class_type} class", 
                        occurence_path(occurence.id), 
                        class: "text-secondary"
                    )%> 
                <% else %>
                    This <%= occurence.gym_class.class_type %> class
                <% end %>
                starts on 
                <%= occurence.start_time.strftime("%A") %> at 
                <%=occurence.start_time.strftime("%l:%M%P")  %> and 
                ends at <%= occurence.end_time.strftime("%l:%M%P") %>.
                This class was created by Coach <%= occurence.user.full_name %>
                <%= time_ago_in_words(occurence.created_at) %> ago.
                <small>
                    <%= pluralize(occurence.bookings.count, "Booking") %>
                </small>
                <small>
                    <% if user_is_admin? %>
                        <% if can?(:delete, occurence) %>    
                                <%= link_to(
                                    "Delete Occurence",
                                    gym_class_occurence_path(@gym_class.id, occurence.id),
                                    method: :delete,
                                    data: {
                                        confirm: "Are you sure you want to delete this occurence?"
                                    }, class: "text-secondary"
                                ) %>
                        <% end %>
                    <% end %>
                </small> <br>
                <% if user_is_coach? %>
                    <small>
                        <% if occurence.active? && can?(:archive, occurence) %>
                            <%= link_to(
                                "Archive Occurence",
                                occurence_occurence_archivings_path(occurence),
                                method: :post,
                                data: {
                                    confirm: "Are you sure you want to archive this occurence?"
                                },
                                class: "text-secondary mb-2"
                                ) 
                            %>
                        <% elsif %>
                            <%= link_to(
                                "Activate Occurence",
                                occurence_occurence_archivings_path(occurence),
                                method: :post,
                                data: {
                                    confirm: "Are you sure you want to activated this occurence?"
                                },
                                class: "text-secondary mb-2"
                            ) %>
                        <% end %>
                    </small>
                <% end %>
            </p>
        </li>
    <% end %>
</ul>