config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get("/", to: "homepage#index", as: :root)

  get("/contact_us", to: "homepage#contact")

  post("/contact_us/process", to: "homepage#process_contact", as: :process_contact)

  resource :session, only: [:new, :create, :destroy]
  resources :users

  resources :bookings, only: [:index] do
    resources :booking_archivings, only: [:create]
    
    get :archived_bookings, on: :collection
  end
  
  resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
    resources :occurence_archivings, shallow: true, only: [:create]
    
    resources :bookings, shallow: true, only: [:create, :destroy] do
      resources :payments, shallow: true, only: [:new, :create]
    end

    get :booked, on: :collection
    get :archived_occurences, on: :collection
  end

  resources :gym_classes do
    resources :occurences, only: [:new, :create, :index, :destroy]
  end


  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create, :show, :index, :update, :destroy] do
        get :current, on: :collection
      end
      
      resources :bookings, only: [:index, :show]  

      resources :occurences, except: [:new, :create, :edit, :update, :destroy] do
        
        resources :bookings, shallow: true, only: [:create, :destroy]

        get :booked, on: :collection
      end

      resources :gym_classes do
        resources :occurences, only: [:new, :create, :index, :destroy]
      end
    
    end
    match "*unmatched", via: :all, to: "application#not_found"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gymook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3" ></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body>
        <header>
          <nav class="navbar navbar-expand-lg navbar-light bg-light text-secondary" >
            <a href="/" class="navbar-brand text-secondary">
              <i class="fas fa-atom fa-spin" ></i>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="toggle-navigation" >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav" >
              <ul class="navbar-nav" >
                <%#li class="nav-item" %>
                    <%#= link_to("Home Page", root_path, class: "nav-link text-secondary") %>
                <%#/li%>
                <% if user_is_coach? %>
                  <li class="nav-item" >
                      <%= link_to("New Gym Class Template", new_gym_class_path, class: "nav-link text-secondary") %>
                  </li>
                  <li class="nav-item" >
                      <%= link_to("Gym Class Templates", gym_classes_path, class: "nav-link text-secondary" ) %>
                  </li>
                  <%#li class="nav-item" %>
                    <%#= link_to("Add a Class", gym_classes_path , class: "nav-link text-secondary" ) %>
                  <%#/li%>
                  <li class="nav-item" >
                      <%= link_to("Classes", occurences_path, class: "text-secondary nav-link") %>
                  </li>
                  <li class="nav-item">
                    <%= link_to("Archived Classes", archived_occurences_occurences_path, class: "nav-link text-secondary") %>
                  </li>
                  <li class="nav-item">
                    <%= link_to("Bookings", bookings_path, class: "nav-link text-secondary") %>
                  </li>
                  <li class="nav-item" >
                    <%= link_to("Achived Bookings", archived_bookings_bookings_path, class: "nav-link text-secondary" ) %>
                  </li>
                <% end %>
                <% if user_signed_in? %>
                  <% if !user_is_coach? %>
                      <li class="nav-item" >
                        <%= link_to("Classes", occurences_path, class: "text-secondary nav-link") %>
                      </li>
                      <li class="nav-item">
                        <%= link_to("Booked Classes", booked_occurences_path, class: "nav-link text-secondary") %>
                      </li>
                  <% end %>
                  <% if user_is_coach? %>
                    <li class="nav-item" >
                      <%= link_to("Users Management", users_path, class: "nav-link text-secondary" ) %>
                    </li>
                  <% end %>
                  <li class="nav-item" >
                    <%= link_to("Hi, #{current_user.first_name}", edit_user_path(current_user), class: "nav-link text-secondary" ) %>
                  </li>
                  <li class="nav-item" >
                    <%= link_to(
                      "Log Out",
                      session_path,
                      method: :delete,
                      data: {
                        confirm: "Are you sure you want to Log Out?"
                      },
                      class: "nav-link text-secondary"
                    ) %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to("Sign In", new_session_path, class: "nav-link text-secondary") %>
                  </li>
                  <li class="nav-item" >
                    <%= link_to("Sign Up", new_user_path, class: "nav-link text-secondary") %>
                  </li>
                  <li class="nav-item">
                    <%= link_to("Contact Us", contact_us_path, class: "nav-link text-secondary") %>
                  </li>
                <% end %>
              </ul>
            </div>
          </nav>
        </header>
    <div id="background-container">
        <main class="container-fluid" style="padding: 0;" >
          <% flash.each do |type, message| %>
            <div class="alert alert-<%= type %>">
              <%= message %>        
            </div>
          <% end %>

          <%= yield %>
        </main>
    </div>
  </body>
</html>